server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/MiniMarket

      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/MiniMarket

        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: 0CeCr2NbRPyLv8jTojuzVXfxZdjknzTy

          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: 0CeCr2NbRPyLv8jTojuzVXfxZdjknzTy